spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: EMPLOYEE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-SERVICE
                fallbackUri: forward:/employeeServiceFallback

        - id: ADDRESS
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/addresses/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: ADDRESS-SERVICE
                fallbackUri: forward:/addressServiceFallback

        - id: AUTH
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

resilience4j:
  timelimiter:
    instances:
      EMPLOYEE-SERVICE:
        timeoutDuration: 5s
      ADDRESS-SERVICE:
        timeoutDuration: 5s
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

      ADDRESS-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka





